#!/bin/bash
echo "1. Go to https://railway.app"
echo "2. Create new project"
echo "3. Connect GitHub repo (or deploy from CLI)"
echo ""
echo "OR use Railway CLI:"
echo "railway login"
echo "railway init"
echo "railway up"
echo ""
echo "Environment variables needed:"
echo "OPENCLAW_GATEWAY_AUTH_TOKEN=your-auth-token"
echo "SLACK_BOT_TOKEN=your-slack-bot-token"
echo "SLACK_SIGNING_SECRET=your-slack-signing-secret"
echo ""
echo "After deploy, get Railway URL and update Slack Request URL"